name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v14.7.0
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '14.7.0'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
